import Head from 'next/head'

import HomeScreen from './components/Home'
export default function Home({data}) {
  return (
    <>
      <Head>
        <title>SGN-TESLA-CLONE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeScreen data={data}/>     
      </main>
    </>
  )
}
export async function getServerSideProps() {
  const { models } = await import("./components/data/data.json");
  return {
    props: {
      data: models,
    },
  };
}
